name: Laravel

on: [push]

jobs:
  laravel-deploy:
    runs-on: ubuntu-latest

    container:
      image: qandend/laravel-deploy-runner:latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: secret
          MYSQL_DATABASE: burak.sh
        ports:
          - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Create SSH KEY
        run: echo "${{ secrets.SSH_PRIVATE_KEY }}" >> priv_key
      - name: Install composer dependencies
        run: |
            composer install --no-scripts
      - name: Prepare Laravel Application
        run: |
            cp .env.example .env
            php artisan key:generate
      - name: Deploy
        run: php artisan deploy
