name: Laravel

on: [push]

jobs:
  laravel-deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: SSH-KEY ADDING
        run: |
          eval $(ssh-agent -s)
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' | ssh-add - > /dev/null
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
      - name: Install composer dependencies
        run: composer install --no-scripts
      - name: Prepare Laravel Application
        run: |
            cp .env.example .env
            php artisan key:generate
      - name: Deploy
        run: php artisan deploy
