name: Laravel

on: [push]

jobs:
  laravel-deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: SSH-KEY ADDING
        run: |
          echo -e "${{ secrets.SSH_PRIVATE_KEY }}" > ~/priv_key
      - name: Install composer dependencies
        run: composer install --no-scripts
      - name: Prepare Laravel Application
        run: |
            cp .env.example .env
            php artisan key:generate
      - name: Deploy
        run: php artisan deploy
