name: Laravel

on: [push]

jobs:
  laravel-deploy:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v1
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
    - name: Prepare Laravel Application
      run: |
        cp .env.example .env
        php artisan key:generate
    - name: Deploy
      run: php artisan deploy
